"""
Artikelnamen die Bring! zelf kent. Zet je zo'n naam in de titel van een
todo-item, dan toont Bring het bijbehorende icoon. Recepten gebruiken
vaak een andere schrijfwijze ("hüttenkäse", "bosuien"), daarom staat er
naast de catalogus een synoniemenlijst die naar de canonieke naam wijst.
"""

# Artikelen die je vrijwel altijd in de kast hebt staan. Ze verdwijnen niet,
# maar komen in het overzicht in een aparte groep die standaard uit staat: zo
# zie je nog wel dat een recept er om vraagt, en kun je hem aantikken als de
# fles bijna leeg is.
#
# De specerijen komen uit wat er daadwerkelijk in de kast staat (bestellingen
# bij De Kruidenbaron), aangevuld met wat daar logisch bij hoort. Gedroogde
# kruiden staan er gewoon tussen: vraagt een recept om een *vers* bosje, dan
# herkent is_pantry_item() dat aan woorden als "verse", "bosje" of "takjes"
# en gaat het alsnog op de boodschappenlijst.
PANTRY = {
    # Olie, azijn en sauzen
    "Olie", "Olijfolie", "Azijn", "Balsamico Azijn", "Rijstazijn",
    "Soja saus", "Ketchup", "Mayonaise", "Mosterd", "Pikante Saus",
    "BBQ Saus", "Honing", "Ahornstroop", "Vissaus", "Sambal", "Harissa",
    "Tahin", "Worcestershiresaus", "Rijstwijn", "Mirin", "Sake", "Miso",
    # Bakken en drogerij
    "Bloem", "Suiker", "Poedersuiker", "Vanillesuiker", "Basterdsuiker",
    "Rietsuiker", "Bakpoeder", "Gist", "Zetmeel", "Paneermeel", "Griesmeel",
    "Vanille", "Cacao", "Kokosrasp", "Speculaaskruiden",
    # Zout en peper
    "Zout", "Peper", "Witte peper", "Zwarte peper",
    "Peperkorrels", "Cayennepeper", "Pfeffer",
    # Gemalen specerijen en zaden
    "Kaneel", "Kurkuma", "Paprikapoeder", "Kruidnagel", "Nootmuskaat",
    "Foelie", "Piment", "Steranijs", "Kardemom", "Laos", "Gemberpoeder",
    "Komijnzaad", "Korianderzaad", "Venkelzaad", "Karwijzaad", "Mosterdzaad",
    "Sesamzaad", "Maanzaad", "Nigellazaad", "Anijszaad", "Sumak", "Saffraan",
    "Asafoetida", "Uienpoeder", "Knoflookpoeder", "Chilipoeder", "Chilivlokken",
    # Kruidenmixen
    "Garam masala", "Kerrie", "Berbere", "Za'atar", "Ras el hanout",
    "Tandoori", "Vijfkruidenpoeder", "Italiaanse kruiden",
    "Provençaalse kruiden", "Nasi kruiden", "Bouillon",
    # Gedroogde kruiden
    "Oregano", "Tijm", "Rozemarijn", "Salie", "Laurierblad", "Marjolein",
    "Dragon", "Bonenkruid", "Basilicum", "Peterselie", "Dille", "Bieslook",
    "Koriander", "Munt",
    # Thee, koffie en kraanwater
    "Thee", "Koffie", "Water",
}

CATALOG = [
    # Groente en fruit
    "Aardappelen", "Aardbeien", "Abrikozen", "Ananas", "Appels", "Artisjokken",
    "Asperges", "Aubergine", "Avocado", "Bananen", "Basilicum", "Bessen",
    "Bieslook", "Blauwe bessen", "Bloemkool", "Bonen", "Bosui / Lente-ui",
    "Broccoli", "Champignons", "Cherrytomaten", "Chillipeper", "Citroen",
    "Courgette", "Cranberry", "Dadels", "Druiven", "Erwten", "Frambozen",
    "Fruit", "Gember", "Grapefruit", "Groenten", "Kersen", "Kiwi", "Knoflook",
    "Komkommer", "Kool", "Koolrabi", "Koriander", "Kruiden", "Limoen", "Maïs",
    "Mandarijnen", "Mango", "Meloen", "Munt", "Nectarine", "Olijven", "Paprika",
    "Passiefruit", "Peren", "Perzik", "Peterselie", "Pompoen", "Prei",
    "Pruimen", "Rabarber", "Radijzen", "Rode biet", "Rucola", "Salie",
    "Selderij", "Sinaasappelen", "Sla", "Sperziebonen", "Spinazie", "Tijm",
    "Tomaten", "Uien", "Venkel", "Vijgen", "Watermeloen", "Witlof", "Wortelen",
    "Zoete aardappelen", "Zwarte bessen",
    # Brood en gebak
    "Amerikaans Broodje", "Bagels", "Bladerdeeg", "Brood", "Croissant",
    "Donuts", "Gesneden brood", "Kadetje", "Muffins", "Pannenkoeken",
    "Pastei / Hartige taart", "Pizza deeg", "Pompoentaart", "Stokbrood",
    "Toast", "Tortillas", "Wafels", "Zoete broodjes",
    # Zuivel en eieren
    "Blauwe kaas", "Boter", "Cheddar", "Creme fraiche", "Eieren", "Feta",
    "Geraspte kaas", "Gorgonzola", "Huttenkaas", "Kaas", "Margarine",
    "Mascarpone", "Melk", "Mozzarella", "Parmezaanse Kaas", "Room", "Roomkaas",
    "Smeerkaas", "Soja melk", "Vla", "Yoghurt", "Zure Room",
    # Vlees en vis
    "Anchovis", "Bitterballen", "Braadworst", "Filet Americain", "Frikadel",
    "Garnalen", "Gehakt", "Gesneden Rundvlees", "Ham", "Hot Dog", "Kalfsvlees",
    "Kalkoen", "Kip", "Kreeft", "Kroket", "Lam", "Mosselen", "Oesters",
    "Prosciutto", "Rundvlees", "Salami", "Spek", "Steak", "Tonijn",
    "Varkensvlees", "Vis", "Vlees", "Vleeswaren", "Worst", "Worsten", "Zalm",
    # Voorraadkast
    "Aardappelpuree", "Ahornstroop", "Amandelen", "Appelmoes", "Augurk",
    "Azijn", "Bakpoeder", "Balsamico Azijn", "BBQ Saus", "Bouillon",
    "Britse bruine saus", "Chutney", "Dip", "Gist", "Hazelnoten", "Jus",
    "Kaneel", "Ketchup", "Kokosmelk", "Linzen", "Mayonaise", "Mosterd",
    "Noten", "Olie", "Olijfolie", "Oregano", "Paneermeel", "Paprikapoeder",
    "Pasta saus", "Peperkorrels", "Pijnboompitten", "Pikante Saus",
    "Pindakaas", "Poedersuiker", "Rozemarijn", "Salade dressing", "Soja saus",
    "Suiker", "Tomatenblokjes", "Tomatenpuree", "Tomatensaus", "Vanillesuiker",
    "Veenbessen saus", "Walnoten", "Witte bonen", "Zetmeel", "Zout",
    # Diepvries en kant-en-klaar
    "Burrito", "Chinees", "Dumplings", "Frieten", "Ijs", "Indische maaltijden",
    "Ingevroren groenten", "Italiaanse maaltijden", "Kippenvleugels",
    "Lasagna", "Mexicaanse maaltijden", "Pizza", "Soep", "Thaise maaltijden",
    "Vissticks", "Witte bonen met tomaat",
    # Granen en pasta
    "Basmati rijst", "Bloem", "Cornflakes", "Couscous", "Cruesli", "Griesmeel",
    "Havermout", "Kikkererwten", "Muesli", "Noedels", "Pasta", "Penne",
    "Rijst", "Risotto rijst", "Spaghetti", "Tofu",
    # Snacks en zoet
    "Chips", "Chocolade", "Crackers", "Dessert", "Gedroogd fruit", "Gelei",
    "Hagelslag", "Honing", "Jam", "Kauwgum", "Kerstkransjes", "Koekjes",
    "Kroepoek", "Mueslireep", "Ontbijtkoek", "Pindanoten", "Popcorn",
    "Pralinécreme", "Snacks", "Stroopwafels", "Taart", "Tortilla Chips",
    "Vanille saus", "Zoetigheid", "Zoute krakeling",
    # Dranken
    "Appelsap", "Bier", "Champagne", "Cider", "Cola", "Drank", "Energiedrank",
    "Fruitsap", "Gemberbier", "Gin", "IJsthee", "Koffie", "Limonade",
    "Mineraalwater", "Prosecco", "Rode wijn", "Rum", "Sinaasappelsap",
    "Smoothie", "Sportdrank", "Sterke drank", "Thee", "Tonic",
    "Warme chocomelk", "Water", "Whisky", "Witte wijn", "Wodka",
    # Huishouden
    "Afwasmiddel", "Aluminium Folie", "Bakpapier", "Batterijen", "Bloemen",
    "Glasreiniger", "Gloeilampen", "Houtskool", "Kaarsen", "Keukenrol",
    "Schoonmaakmiddelen", "Servetten", "Spons", "Vaatwasser tabletten",
    "Vershoudfolie", "Vuilniszakken", "Waspoeder", "Wasverzachter",
]

# Woorden zoals recepten ze schrijven -> naam zoals Bring hem kent.
# Deze winnen van de automatisch afgeleide enkelvoud/meervoud-varianten.
SYNONYMS = {
    # Groente en fruit
    "ui": "Uien",
    "rode ui": "Uien",
    "bosui": "Bosui / Lente-ui",
    "bosuien": "Bosui / Lente-ui",
    "lente-ui": "Bosui / Lente-ui",
    "lenteui": "Bosui / Lente-ui",
    "tomaat": "Tomaten",
    "cherrytomaatjes": "Cherrytomaten",
    "wortel": "Wortelen",
    "winterwortel": "Wortelen",
    "peen": "Wortelen",
    "appel": "Appels",
    "peer": "Peren",
    "sinaasappel": "Sinaasappelen",
    "mandarijn": "Mandarijnen",
    "aardappel": "Aardappelen",
    "zoete aardappel": "Zoete aardappelen",
    "champignon": "Champignons",
    "chinese kool": "Kool",
    "witte kool": "Kool",
    "rode kool": "Kool",
    "rodekool": "Kool",
    "spitskool": "Kool",
    "paksoi": "Kool",
    "sperzieboon": "Sperziebonen",
    "haricots verts": "Sperziebonen",
    "radijs": "Radijzen",
    "sjalot": "Uien",
    "sjalotten": "Uien",
    "zilveruitjes": "Uien",
    "winterpeen": "Wortelen",
    "bospeen": "Wortelen",
    "waspeen": "Wortelen",
    "trostomaten": "Tomaten",
    "pruimtomaten": "Tomaten",
    "roma tomaten": "Tomaten",
    "bleekselderij": "Selderij",
    "knolselderij": "Knolselderij",
    "ijsbergsla": "Sla",
    "veldsla": "Sla",
    "romaine": "Sla",
    "little gem": "Sla",
    "kropsla": "Sla",
    "savooiekool": "Kool",
    "boerenkool": "Kool",
    "rodekool": "Kool",
    "kastanjechampignons": "Champignons",
    "roerbakgroente": "Groenten",
    "roerbakgroenten": "Groenten",
    "wokgroente": "Groenten",
    "wokgroenten": "Groenten",
    "soepgroente": "Groenten",
    "jackfruit": "Jackfruit",
    "quinoa": "Quinoa",
    "bulgur": "Bulgur",
    "couscous": "Couscous",
    "misopasta": "Miso",
    "miso": "Miso",
    "portobello": "Champignons",
    "doperwten": "Erwten",
    "tuinbonen": "Bonen",
    "kidneybonen": "Bonen",
    "borlottibonen": "Bonen",
    "cannellinibonen": "Bonen",
    "bruine bonen": "Bonen",
    "zwarte bonen": "Bonen",
    "rode linzen": "Linzen",
    "groene linzen": "Linzen",
    "belugalinzen": "Linzen",
    "blauwe bes": "Blauwe bessen",
    "framboos": "Frambozen",
    "aardbei": "Aardbeien",
    "banaan": "Bananen",
    "peertje": "Peren",
    "druif": "Druiven",
    "olijven": "Olijven",
    # Voedingscentrum schrijft olijfolie als "(olijf)olie"; zonder deze regel
    # wint "olijf" en belandt de olie onder Olijven.
    "(olijf)olie": "Olijfolie",
    "verse munt": "Munt",
    "verse koriander": "Koriander",
    "verse basilicum": "Basilicum",
    "rode peper": "Chillipeper",
    "chilipeper": "Chillipeper",
    "chilivlokken": "Chillipeper",
    # Zuivel
    "hüttenkäse": "Huttenkaas",
    "huttenkase": "Huttenkaas",
    "cottage cheese": "Huttenkaas",
    "cottagecheese": "Huttenkaas",
    "oude kaas": "Kaas",
    "jonge kaas": "Kaas",
    "belegen kaas": "Kaas",
    "parmezaan": "Parmezaanse Kaas",
    "crème fraîche": "Creme fraiche",
    "griekse yoghurt": "Yoghurt",
    "volle yoghurt": "Yoghurt",
    "magere yoghurt": "Yoghurt",
    "ei": "Eieren",
    "eitjes": "Eieren",
    "vloeibare margarine": "Margarine",
    "roomboter": "Boter",
    "ongezouten boter": "Boter",
    "ricotta": "Roomkaas",
    "slagroom": "Room",
    "kookroom": "Room",
    "zure room": "Zure Room",
    "geitenkaas": "Kaas",
    "pecorino": "Kaas",
    "gruyere": "Kaas",
    "emmentaler": "Kaas",
    "halloumi": "Kaas",
    "karnemelk": "Melk",
    "havermelk": "Soja melk",
    "amandelmelk": "Soja melk",
    # Granen en pasta
    "tagliatelle": "Pasta",
    "macaroni": "Pasta",
    "volkoren pasta": "Pasta",
    "fusilli": "Pasta",
    "farfalle": "Pasta",
    "rigatoni": "Pasta",
    "tagliatelli": "Pasta",
    "orzo": "Pasta",
    "volkorenorzo": "Pasta",
    "schelpjespasta": "Pasta",
    "lasagnebladen": "Lasagna",
    "zilvervliesrijst": "Rijst",
    "basmatirijst": "Basmati rijst",
    # Rijstnoedels zijn noedels, geen rijst - zonder deze regel wint "rijst".
    "rijstnoedels": "Noedels",
    "mihoen": "Noedels",
    "vermicelli": "Noedels",
    "tarwenoedels": "Noedels",
    "noodles": "Noedels",
    "noedels": "Noedels",
    "ramen": "Noedels",
    "udon": "Noedels",
    "soba": "Noedels",
    "bami": "Noedels",
    "eiernoedels": "Noedels",
    "mie": "Noedels",
    # Zonder deze regels wint het kortere "mosterd" resp. "kokos" en belandt
    # het zaad of de melk onder het verkeerde artikel.
    "mosterdzaad": "Mosterdzaad",
    "sesamzaad": "Sesamzaad",
    # Voorraadkast
    "sojasaus": "Soja saus",
    "ketjap": "Soja saus",
    "ketjap manis": "Soja saus",
    "zonnebloemolie": "Olie",
    "sesamolie": "Olie",
    "bakolie": "Olie",
    "arachideolie": "Olie",
    "raapzaadolie": "Olie",
    "koolzaadolie": "Olie",
    "bouillontablet": "Bouillon",
    "bouillonblokje": "Bouillon",
    "groentebouillon": "Bouillon",
    # Ook hier zet Voedingscentrum een deel tussen haakjes vooraan, waardoor
    # anders "(groente)" wint en het tablet onder Groenten belandt.
    "(groente)bouillontablet": "Bouillon",
    "(groente)bouillonblokje": "Bouillon",
    "(groente)bouillon": "Bouillon",
    "gedroogde linzen": "Linzen",
    "kikkererwt": "Kikkererwten",
    "pinda": "Pindanoten",
    "pinda's": "Pindanoten",
    "pindas": "Pindanoten",
    "walnoot": "Walnoten",
    "hazelnoot": "Hazelnoten",
    "amandel": "Amandelen",
    # Vlees, vis en vega
    "kipfilet": "Kip",
    "kipdijfilet": "Kip",
    "gerookte zalm": "Zalm",
    "vegetarisch gehakt": "Gehakt",
    "vegetarische gehakt": "Gehakt",
    "biefstuk": "Steak",
    "entrecote": "Steak",
    "kippendijen": "Kip",
    "kipreepjes": "Kip",
    "kipgehakt": "Gehakt",
    "rundergehakt": "Gehakt",
    "half-om-half gehakt": "Gehakt",
    "spekjes": "Spek",
    "spekblokjes": "Spek",
    "pancetta": "Spek",
    "chorizo": "Worst",
    "rookworst": "Worst",
    "zalmfilet": "Zalm",
    "kabeljauw": "Vis",
    "witvis": "Vis",
    "ansjovis": "Anchovis",
    "edamamebonen": "Bonen",
    # Specerijen in poedervorm. Zonder deze regels wint het kortere woord en
    # belandt knoflookpoeder onder de verse knoflook, venkelzaad onder de
    # venkel uit de groenteschap en korianderpoeder onder het verse bosje.
    "knoflookpoeder": "Knoflookpoeder",
    "uienpoeder": "Uienpoeder",
    "gemberpoeder": "Gemberpoeder",
    "gemalen gember": "Gemberpoeder",
    "venkelzaad": "Venkelzaad",
    "korianderzaad": "Korianderzaad",
    "korianderpoeder": "Korianderzaad",
    "gemalen koriander": "Korianderzaad",
    "komijnpoeder": "Komijnzaad",
    "gemalen komijn": "Komijnzaad",
    "djinten": "Komijnzaad",
    "selderijzout": "Zout",
    "uienpoeder gemalen": "Uienpoeder",
    # Zout en peper zoals recepten ze schrijven
    "zeezout": "Zout",
    "grof zout": "Zout",
    "keukenzout": "Zout",
    "tafelzout": "Zout",
    # Let op: geen synoniem voor "zwarte peper" naar "Peper". Dat zou winnen
    # van "peper en zout", omdat het eerder in de regel begint. "Zwarte peper"
    # staat daarom als eigen naam in PANTRY.
    "cayennepeper": "Cayennepeper",
    "cayenne": "Cayennepeper",
    # Losse specerijen en zaden
    "kruidnagel": "Kruidnagel",
    "kruidnagels": "Kruidnagel",
    "kruidnagelpoeder": "Kruidnagel",
    "karwijzaad": "Karwijzaad",
    "kummel": "Karwijzaad",
    "kummelzaad": "Karwijzaad",
    "sumak": "Sumak",
    "sumac": "Sumak",
    "steranijs": "Steranijs",
    "anijszaad": "Anijszaad",
    "maanzaad": "Maanzaad",
    "nigella": "Nigellazaad",
    "nigellazaad": "Nigellazaad",
    "zwarte komijn": "Nigellazaad",
    "piment": "Piment",
    "foelie": "Foelie",
    "saffraan": "Saffraan",
    "galangawortel": "Laos",
    "galanga": "Laos",
    "kokosrasp": "Kokosrasp",
    "geraspte kokos": "Kokosrasp",
    "kokos geraspt": "Kokosrasp",
    # Kruidenmixen
    "kerrie": "Kerrie",
    "kerriepoeder": "Kerrie",
    "currypoeder": "Kerrie",
    "curry poeder": "Kerrie",
    "italiaanse kruiden": "Italiaanse kruiden",
    "provencaalse kruiden": "Provençaalse kruiden",
    "provençaalse kruiden": "Provençaalse kruiden",
    "herbes de provence": "Provençaalse kruiden",
    "kruiden de provence": "Provençaalse kruiden",
    "nasi kruiden": "Nasi kruiden",
    "nasi kruidenmix": "Nasi kruiden",
    "bami kruiden": "Nasi kruiden",
    "ras el hanout": "Ras el hanout",
    "tandoori": "Tandoori",
    "tandoorikruiden": "Tandoori",
    "vijfkruidenpoeder": "Vijfkruidenpoeder",
    "five spice": "Vijfkruidenpoeder",
    "speculaaskruiden": "Speculaaskruiden",
    "koekkruiden": "Speculaaskruiden",
    "bouillonpoeder": "Bouillon",
    "kippenbouillon": "Bouillon",
    "runderbouillon": "Bouillon",
    # Potjes en flessen uit de kast
    "sambal": "Sambal",
    "sambal oelek": "Sambal",
    "harissa": "Harissa",
    "tahin": "Tahin",
    "tahini": "Tahin",
    "worcestershiresaus": "Worcestershiresaus",
    "rijstazijn": "Rijstazijn",
    # Rijstwijn is geen rijst; zonder deze regels wint het kortere woord.
    "rijstwijn": "Rijstwijn",
    "shaoxing": "Rijstwijn",
    "mirin": "Mirin",
    "sake": "Sake",
    "witte wijnazijn": "Azijn",
    "witte wijn azijn": "Azijn",
    "wittewijnazijn": "Azijn",
    "rodewijnazijn": "Azijn",
    # Voedingscentrum schrijft "(wijn)azijn", net als "(olijf)olie".
    "(wijn)azijn": "Azijn",
    "rode wijnazijn": "Azijn",
    "rode wijn azijn": "Azijn",
    "wijnazijn": "Azijn",
    "appelazijn": "Azijn",
    "balsamicoazijn": "Balsamico Azijn",
    "balsamico azijn": "Balsamico Azijn",
    "vanille-extract": "Vanille",
    "vanille extract": "Vanille",
    "vanillestokje": "Vanille",
    "cacaopoeder": "Cacao",
    # Overig
    "maizena": "Zetmeel",
    "maïzena": "Zetmeel",
    # Zonder deze regels wint "mais" en belandt het zetmeel bij de maiskorrels.
    "maiszetmeel": "Zetmeel",
    "maïszetmeel": "Zetmeel",
    "aardappelzetmeel": "Zetmeel",
    # "peper en zout" wordt door expand_ingredient() in twee boodschappen
    # gesplitst, dus die woorden moeten los herkenbaar zijn.
    "peper": "Peper",
    "zout": "Zout",
    "witte peper": "Witte peper",
    "zwarte peper": "Zwarte peper",
}
